/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: blinds.proto */

#ifndef PROTOBUF_C_blinds_2eproto__INCLUDED
#define PROTOBUF_C_blinds_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct ClientConfig ClientConfig;
typedef struct CoverConfig CoverConfig;
typedef struct LoraClientOperationMessage LoraClientOperationMessage;
typedef struct ClientRegister ClientRegister;
typedef struct ClientAvailable ClientAvailable;
typedef struct ClientBattery ClientBattery;
typedef struct CoverPosition CoverPosition;
typedef struct LoraClientResponseMessage LoraClientResponseMessage;


/* --- enums --- */

typedef enum _CoverOperation {
  COVER_OPERATION__CMD_OPEN = 0,
  COVER_OPERATION__CMD_CLOSE = 1,
  COVER_OPERATION__CMD_STOP = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COVER_OPERATION)
} CoverOperation;
typedef enum _ClientOperation {
  CLIENT_OPERATION__CMD_ENABLE_WIFI = 0,
  CLIENT_OPERATION__CMD_DISABLE_WIFI = 1,
  CLIENT_OPERATION__CMD_OTA = 2,
  CLIENT_OPERATION__CMD_STATUS = 3,
  CLIENT_OPERATION__CMD_SLEEP = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLIENT_OPERATION)
} ClientOperation;

/* --- messages --- */

struct  ClientConfig
{
  ProtobufCMessage base;
  uint32_t addr;
  uint32_t subnt;
  ProtobufCBinaryData name;
  uint64_t sleepduration;
};
#define CLIENT_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_config__descriptor) \
    , 0, 0, {0,NULL}, 0 }


struct  CoverConfig
{
  ProtobufCMessage base;
  uint32_t opentime;
  uint32_t closetime;
};
#define COVER_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cover_config__descriptor) \
    , 0, 0 }


typedef enum {
  LORA_CLIENT_OPERATION_MESSAGE__CMD__NOT_SET = 0,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_OPERATION = 10,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_SYSOP = 11,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_CLIENTCONFIG = 12,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_COVERCONFIG = 13
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA_CLIENT_OPERATION_MESSAGE__CMD__CASE)
} LoraClientOperationMessage__CmdCase;

struct  LoraClientOperationMessage
{
  ProtobufCMessage base;
  uint32_t destaddress;
  uint32_t destsubnet;
  uint32_t senderaddress;
  uint32_t msgid;
  LoraClientOperationMessage__CmdCase cmd_case;
  union {
    ClientConfig *clientconfig;
    CoverConfig *coverconfig;
    CoverOperation operation;
    ClientOperation sysop;
  };
};
#define LORA_CLIENT_OPERATION_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora_client_operation_message__descriptor) \
    , 0, 0, 0, 0, LORA_CLIENT_OPERATION_MESSAGE__CMD__NOT_SET, {0} }


struct  ClientRegister
{
  ProtobufCMessage base;
  uint64_t mac_addr;
};
#define CLIENT_REGISTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_register__descriptor) \
    , 0 }


struct  ClientAvailable
{
  ProtobufCMessage base;
  protobuf_c_boolean available;
};
#define CLIENT_AVAILABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_available__descriptor) \
    , 0 }


struct  ClientBattery
{
  ProtobufCMessage base;
  float voltage;
};
#define CLIENT_BATTERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_battery__descriptor) \
    , 0 }


struct  CoverPosition
{
  ProtobufCMessage base;
  float position;
};
#define COVER_POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cover_position__descriptor) \
    , 0 }


typedef enum {
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO__NOT_SET = 0,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_AVAIL = 10,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_REGISTER = 11,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_STATE = 12,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_POSITION = 13
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA_CLIENT_RESPONSE_MESSAGE__PROTO__CASE)
} LoraClientResponseMessage__ProtoCase;

struct  LoraClientResponseMessage
{
  ProtobufCMessage base;
  uint32_t destaddress;
  uint32_t destsubnet;
  uint32_t senderaddress;
  uint32_t msgid;
  LoraClientResponseMessage__ProtoCase proto_case;
  union {
    ClientAvailable *avail;
    CoverPosition *position;
    ClientRegister *register_;
    ClientBattery *state;
  };
};
#define LORA_CLIENT_RESPONSE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora_client_response_message__descriptor) \
    , 0, 0, 0, 0, LORA_CLIENT_RESPONSE_MESSAGE__PROTO__NOT_SET, {0} }


/* ClientConfig methods */
void   client_config__init
                     (ClientConfig         *message);
size_t client_config__get_packed_size
                     (const ClientConfig   *message);
size_t client_config__pack
                     (const ClientConfig   *message,
                      uint8_t             *out);
size_t client_config__pack_to_buffer
                     (const ClientConfig   *message,
                      ProtobufCBuffer     *buffer);
ClientConfig *
       client_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_config__free_unpacked
                     (ClientConfig *message,
                      ProtobufCAllocator *allocator);
/* CoverConfig methods */
void   cover_config__init
                     (CoverConfig         *message);
size_t cover_config__get_packed_size
                     (const CoverConfig   *message);
size_t cover_config__pack
                     (const CoverConfig   *message,
                      uint8_t             *out);
size_t cover_config__pack_to_buffer
                     (const CoverConfig   *message,
                      ProtobufCBuffer     *buffer);
CoverConfig *
       cover_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cover_config__free_unpacked
                     (CoverConfig *message,
                      ProtobufCAllocator *allocator);
/* LoraClientOperationMessage methods */
void   lora_client_operation_message__init
                     (LoraClientOperationMessage         *message);
size_t lora_client_operation_message__get_packed_size
                     (const LoraClientOperationMessage   *message);
size_t lora_client_operation_message__pack
                     (const LoraClientOperationMessage   *message,
                      uint8_t             *out);
size_t lora_client_operation_message__pack_to_buffer
                     (const LoraClientOperationMessage   *message,
                      ProtobufCBuffer     *buffer);
LoraClientOperationMessage *
       lora_client_operation_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora_client_operation_message__free_unpacked
                     (LoraClientOperationMessage *message,
                      ProtobufCAllocator *allocator);
/* ClientRegister methods */
void   client_register__init
                     (ClientRegister         *message);
size_t client_register__get_packed_size
                     (const ClientRegister   *message);
size_t client_register__pack
                     (const ClientRegister   *message,
                      uint8_t             *out);
size_t client_register__pack_to_buffer
                     (const ClientRegister   *message,
                      ProtobufCBuffer     *buffer);
ClientRegister *
       client_register__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_register__free_unpacked
                     (ClientRegister *message,
                      ProtobufCAllocator *allocator);
/* ClientAvailable methods */
void   client_available__init
                     (ClientAvailable         *message);
size_t client_available__get_packed_size
                     (const ClientAvailable   *message);
size_t client_available__pack
                     (const ClientAvailable   *message,
                      uint8_t             *out);
size_t client_available__pack_to_buffer
                     (const ClientAvailable   *message,
                      ProtobufCBuffer     *buffer);
ClientAvailable *
       client_available__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_available__free_unpacked
                     (ClientAvailable *message,
                      ProtobufCAllocator *allocator);
/* ClientBattery methods */
void   client_battery__init
                     (ClientBattery         *message);
size_t client_battery__get_packed_size
                     (const ClientBattery   *message);
size_t client_battery__pack
                     (const ClientBattery   *message,
                      uint8_t             *out);
size_t client_battery__pack_to_buffer
                     (const ClientBattery   *message,
                      ProtobufCBuffer     *buffer);
ClientBattery *
       client_battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_battery__free_unpacked
                     (ClientBattery *message,
                      ProtobufCAllocator *allocator);
/* CoverPosition methods */
void   cover_position__init
                     (CoverPosition         *message);
size_t cover_position__get_packed_size
                     (const CoverPosition   *message);
size_t cover_position__pack
                     (const CoverPosition   *message,
                      uint8_t             *out);
size_t cover_position__pack_to_buffer
                     (const CoverPosition   *message,
                      ProtobufCBuffer     *buffer);
CoverPosition *
       cover_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cover_position__free_unpacked
                     (CoverPosition *message,
                      ProtobufCAllocator *allocator);
/* LoraClientResponseMessage methods */
void   lora_client_response_message__init
                     (LoraClientResponseMessage         *message);
size_t lora_client_response_message__get_packed_size
                     (const LoraClientResponseMessage   *message);
size_t lora_client_response_message__pack
                     (const LoraClientResponseMessage   *message,
                      uint8_t             *out);
size_t lora_client_response_message__pack_to_buffer
                     (const LoraClientResponseMessage   *message,
                      ProtobufCBuffer     *buffer);
LoraClientResponseMessage *
       lora_client_response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora_client_response_message__free_unpacked
                     (LoraClientResponseMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ClientConfig_Closure)
                 (const ClientConfig *message,
                  void *closure_data);
typedef void (*CoverConfig_Closure)
                 (const CoverConfig *message,
                  void *closure_data);
typedef void (*LoraClientOperationMessage_Closure)
                 (const LoraClientOperationMessage *message,
                  void *closure_data);
typedef void (*ClientRegister_Closure)
                 (const ClientRegister *message,
                  void *closure_data);
typedef void (*ClientAvailable_Closure)
                 (const ClientAvailable *message,
                  void *closure_data);
typedef void (*ClientBattery_Closure)
                 (const ClientBattery *message,
                  void *closure_data);
typedef void (*CoverPosition_Closure)
                 (const CoverPosition *message,
                  void *closure_data);
typedef void (*LoraClientResponseMessage_Closure)
                 (const LoraClientResponseMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    cover_operation__descriptor;
extern const ProtobufCEnumDescriptor    client_operation__descriptor;
extern const ProtobufCMessageDescriptor client_config__descriptor;
extern const ProtobufCMessageDescriptor cover_config__descriptor;
extern const ProtobufCMessageDescriptor lora_client_operation_message__descriptor;
extern const ProtobufCMessageDescriptor client_register__descriptor;
extern const ProtobufCMessageDescriptor client_available__descriptor;
extern const ProtobufCMessageDescriptor client_battery__descriptor;
extern const ProtobufCMessageDescriptor cover_position__descriptor;
extern const ProtobufCMessageDescriptor lora_client_response_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_blinds_2eproto__INCLUDED */
