/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: blinds.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "blinds.pb-c.h"
void   client_config__init
                     (ClientConfig         *message)
{
  static const ClientConfig init_value = CLIENT_CONFIG__INIT;
  *message = init_value;
}
size_t client_config__get_packed_size
                     (const ClientConfig *message)
{
  assert(message->base.descriptor == &client_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_config__pack
                     (const ClientConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_config__pack_to_buffer
                     (const ClientConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientConfig *
       client_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientConfig *)
     protobuf_c_message_unpack (&client_config__descriptor,
                                allocator, len, data);
}
void   client_config__free_unpacked
                     (ClientConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cover_config__init
                     (CoverConfig         *message)
{
  static const CoverConfig init_value = COVER_CONFIG__INIT;
  *message = init_value;
}
size_t cover_config__get_packed_size
                     (const CoverConfig *message)
{
  assert(message->base.descriptor == &cover_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cover_config__pack
                     (const CoverConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cover_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cover_config__pack_to_buffer
                     (const CoverConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cover_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CoverConfig *
       cover_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CoverConfig *)
     protobuf_c_message_unpack (&cover_config__descriptor,
                                allocator, len, data);
}
void   cover_config__free_unpacked
                     (CoverConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cover_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora_client_operation_message__init
                     (LoraClientOperationMessage         *message)
{
  static const LoraClientOperationMessage init_value = LORA_CLIENT_OPERATION_MESSAGE__INIT;
  *message = init_value;
}
size_t lora_client_operation_message__get_packed_size
                     (const LoraClientOperationMessage *message)
{
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora_client_operation_message__pack
                     (const LoraClientOperationMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora_client_operation_message__pack_to_buffer
                     (const LoraClientOperationMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoraClientOperationMessage *
       lora_client_operation_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoraClientOperationMessage *)
     protobuf_c_message_unpack (&lora_client_operation_message__descriptor,
                                allocator, len, data);
}
void   lora_client_operation_message__free_unpacked
                     (LoraClientOperationMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_register__init
                     (ClientRegister         *message)
{
  static const ClientRegister init_value = CLIENT_REGISTER__INIT;
  *message = init_value;
}
size_t client_register__get_packed_size
                     (const ClientRegister *message)
{
  assert(message->base.descriptor == &client_register__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_register__pack
                     (const ClientRegister *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_register__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_register__pack_to_buffer
                     (const ClientRegister *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_register__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientRegister *
       client_register__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientRegister *)
     protobuf_c_message_unpack (&client_register__descriptor,
                                allocator, len, data);
}
void   client_register__free_unpacked
                     (ClientRegister *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_register__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_available__init
                     (ClientAvailable         *message)
{
  static const ClientAvailable init_value = CLIENT_AVAILABLE__INIT;
  *message = init_value;
}
size_t client_available__get_packed_size
                     (const ClientAvailable *message)
{
  assert(message->base.descriptor == &client_available__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_available__pack
                     (const ClientAvailable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_available__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_available__pack_to_buffer
                     (const ClientAvailable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_available__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientAvailable *
       client_available__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientAvailable *)
     protobuf_c_message_unpack (&client_available__descriptor,
                                allocator, len, data);
}
void   client_available__free_unpacked
                     (ClientAvailable *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_available__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_battery__init
                     (ClientBattery         *message)
{
  static const ClientBattery init_value = CLIENT_BATTERY__INIT;
  *message = init_value;
}
size_t client_battery__get_packed_size
                     (const ClientBattery *message)
{
  assert(message->base.descriptor == &client_battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_battery__pack
                     (const ClientBattery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_battery__pack_to_buffer
                     (const ClientBattery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientBattery *
       client_battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientBattery *)
     protobuf_c_message_unpack (&client_battery__descriptor,
                                allocator, len, data);
}
void   client_battery__free_unpacked
                     (ClientBattery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cover_position__init
                     (CoverPosition         *message)
{
  static const CoverPosition init_value = COVER_POSITION__INIT;
  *message = init_value;
}
size_t cover_position__get_packed_size
                     (const CoverPosition *message)
{
  assert(message->base.descriptor == &cover_position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cover_position__pack
                     (const CoverPosition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cover_position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cover_position__pack_to_buffer
                     (const CoverPosition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cover_position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CoverPosition *
       cover_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CoverPosition *)
     protobuf_c_message_unpack (&cover_position__descriptor,
                                allocator, len, data);
}
void   cover_position__free_unpacked
                     (CoverPosition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cover_position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora_client_response_message__init
                     (LoraClientResponseMessage         *message)
{
  static const LoraClientResponseMessage init_value = LORA_CLIENT_RESPONSE_MESSAGE__INIT;
  *message = init_value;
}
size_t lora_client_response_message__get_packed_size
                     (const LoraClientResponseMessage *message)
{
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora_client_response_message__pack
                     (const LoraClientResponseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora_client_response_message__pack_to_buffer
                     (const LoraClientResponseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoraClientResponseMessage *
       lora_client_response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoraClientResponseMessage *)
     protobuf_c_message_unpack (&lora_client_response_message__descriptor,
                                allocator, len, data);
}
void   lora_client_response_message__free_unpacked
                     (LoraClientResponseMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client_config__field_descriptors[4] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subnt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, subnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sleepDuration",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, sleepduration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_config__field_indices_by_name[] = {
  0,   /* field[0] = addr */
  2,   /* field[2] = name */
  3,   /* field[3] = sleepDuration */
  1,   /* field[1] = subnt */
};
static const ProtobufCIntRange client_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor client_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientConfig",
  "ClientConfig",
  "ClientConfig",
  "",
  sizeof(ClientConfig),
  4,
  client_config__field_descriptors,
  client_config__field_indices_by_name,
  1,  client_config__number_ranges,
  (ProtobufCMessageInit) client_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cover_config__field_descriptors[2] =
{
  {
    "openTime",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, opentime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeTime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, closetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cover_config__field_indices_by_name[] = {
  1,   /* field[1] = closeTime */
  0,   /* field[0] = openTime */
};
static const ProtobufCIntRange cover_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cover_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CoverConfig",
  "CoverConfig",
  "CoverConfig",
  "",
  sizeof(CoverConfig),
  2,
  cover_config__field_descriptors,
  cover_config__field_indices_by_name,
  1,  cover_config__number_ranges,
  (ProtobufCMessageInit) cover_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora_client_operation_message__field_descriptors[8] =
{
  {
    "destAddress",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientOperationMessage, destaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destSubnet",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientOperationMessage, destsubnet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "senderAddress",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientOperationMessage, senderaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientOperationMessage, msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operation",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, operation),
    &cover_operation__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sysop",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, sysop),
    &client_operation__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientconfig",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, clientconfig),
    &client_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coverconfig",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, coverconfig),
    &cover_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora_client_operation_message__field_indices_by_name[] = {
  6,   /* field[6] = clientconfig */
  7,   /* field[7] = coverconfig */
  0,   /* field[0] = destAddress */
  1,   /* field[1] = destSubnet */
  3,   /* field[3] = msgId */
  4,   /* field[4] = operation */
  2,   /* field[2] = senderAddress */
  5,   /* field[5] = sysop */
};
static const ProtobufCIntRange lora_client_operation_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 4 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor lora_client_operation_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoraClientOperationMessage",
  "LoraClientOperationMessage",
  "LoraClientOperationMessage",
  "",
  sizeof(LoraClientOperationMessage),
  8,
  lora_client_operation_message__field_descriptors,
  lora_client_operation_message__field_indices_by_name,
  2,  lora_client_operation_message__number_ranges,
  (ProtobufCMessageInit) lora_client_operation_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_register__field_descriptors[1] =
{
  {
    "mac_addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ClientRegister, mac_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_register__field_indices_by_name[] = {
  0,   /* field[0] = mac_addr */
};
static const ProtobufCIntRange client_register__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_register__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientRegister",
  "ClientRegister",
  "ClientRegister",
  "",
  sizeof(ClientRegister),
  1,
  client_register__field_descriptors,
  client_register__field_indices_by_name,
  1,  client_register__number_ranges,
  (ProtobufCMessageInit) client_register__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_available__field_descriptors[1] =
{
  {
    "available",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientAvailable, available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_available__field_indices_by_name[] = {
  0,   /* field[0] = available */
};
static const ProtobufCIntRange client_available__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_available__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientAvailable",
  "ClientAvailable",
  "ClientAvailable",
  "",
  sizeof(ClientAvailable),
  1,
  client_available__field_descriptors,
  client_available__field_indices_by_name,
  1,  client_available__number_ranges,
  (ProtobufCMessageInit) client_available__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_battery__field_descriptors[1] =
{
  {
    "voltage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ClientBattery, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_battery__field_indices_by_name[] = {
  0,   /* field[0] = voltage */
};
static const ProtobufCIntRange client_battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientBattery",
  "ClientBattery",
  "ClientBattery",
  "",
  sizeof(ClientBattery),
  1,
  client_battery__field_descriptors,
  client_battery__field_indices_by_name,
  1,  client_battery__number_ranges,
  (ProtobufCMessageInit) client_battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cover_position__field_descriptors[1] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CoverPosition, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cover_position__field_indices_by_name[] = {
  0,   /* field[0] = position */
};
static const ProtobufCIntRange cover_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cover_position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CoverPosition",
  "CoverPosition",
  "CoverPosition",
  "",
  sizeof(CoverPosition),
  1,
  cover_position__field_descriptors,
  cover_position__field_indices_by_name,
  1,  cover_position__number_ranges,
  (ProtobufCMessageInit) cover_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora_client_response_message__field_descriptors[8] =
{
  {
    "destAddress",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientResponseMessage, destaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destSubnet",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientResponseMessage, destsubnet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "senderAddress",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientResponseMessage, senderaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraClientResponseMessage, msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, avail),
    &client_available__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, register_),
    &client_register__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, state),
    &client_battery__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, position),
    &cover_position__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora_client_response_message__field_indices_by_name[] = {
  4,   /* field[4] = avail */
  0,   /* field[0] = destAddress */
  1,   /* field[1] = destSubnet */
  3,   /* field[3] = msgId */
  7,   /* field[7] = position */
  5,   /* field[5] = register */
  2,   /* field[2] = senderAddress */
  6,   /* field[6] = state */
};
static const ProtobufCIntRange lora_client_response_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 4 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor lora_client_response_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoraClientResponseMessage",
  "LoraClientResponseMessage",
  "LoraClientResponseMessage",
  "",
  sizeof(LoraClientResponseMessage),
  8,
  lora_client_response_message__field_descriptors,
  lora_client_response_message__field_indices_by_name,
  2,  lora_client_response_message__number_ranges,
  (ProtobufCMessageInit) lora_client_response_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cover_operation__enum_values_by_number[3] =
{
  { "CMD_OPEN", "COVER_OPERATION__CMD_OPEN", 0 },
  { "CMD_CLOSE", "COVER_OPERATION__CMD_CLOSE", 1 },
  { "CMD_STOP", "COVER_OPERATION__CMD_STOP", 2 },
};
static const ProtobufCIntRange cover_operation__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex cover_operation__enum_values_by_name[3] =
{
  { "CMD_CLOSE", 1 },
  { "CMD_OPEN", 0 },
  { "CMD_STOP", 2 },
};
const ProtobufCEnumDescriptor cover_operation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CoverOperation",
  "CoverOperation",
  "CoverOperation",
  "",
  3,
  cover_operation__enum_values_by_number,
  3,
  cover_operation__enum_values_by_name,
  1,
  cover_operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_operation__enum_values_by_number[5] =
{
  { "CMD_ENABLE_WIFI", "CLIENT_OPERATION__CMD_ENABLE_WIFI", 0 },
  { "CMD_DISABLE_WIFI", "CLIENT_OPERATION__CMD_DISABLE_WIFI", 1 },
  { "CMD_OTA", "CLIENT_OPERATION__CMD_OTA", 2 },
  { "CMD_STATUS", "CLIENT_OPERATION__CMD_STATUS", 3 },
  { "CMD_SLEEP", "CLIENT_OPERATION__CMD_SLEEP", 4 },
};
static const ProtobufCIntRange client_operation__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex client_operation__enum_values_by_name[5] =
{
  { "CMD_DISABLE_WIFI", 1 },
  { "CMD_ENABLE_WIFI", 0 },
  { "CMD_OTA", 2 },
  { "CMD_SLEEP", 4 },
  { "CMD_STATUS", 3 },
};
const ProtobufCEnumDescriptor client_operation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientOperation",
  "ClientOperation",
  "ClientOperation",
  "",
  5,
  client_operation__enum_values_by_number,
  5,
  client_operation__enum_values_by_name,
  1,
  client_operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
