/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: blinds.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "blinds.pb-c.h"
void   lora_cover_operation__init
                     (LoraCoverOperation         *message)
{
  static const LoraCoverOperation init_value = LORA_COVER_OPERATION__INIT;
  *message = init_value;
}
size_t lora_cover_operation__get_packed_size
                     (const LoraCoverOperation *message)
{
  assert(message->base.descriptor == &lora_cover_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora_cover_operation__pack
                     (const LoraCoverOperation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora_cover_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora_cover_operation__pack_to_buffer
                     (const LoraCoverOperation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora_cover_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoraCoverOperation *
       lora_cover_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoraCoverOperation *)
     protobuf_c_message_unpack (&lora_cover_operation__descriptor,
                                allocator, len, data);
}
void   lora_cover_operation__free_unpacked
                     (LoraCoverOperation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora_cover_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_config__init
                     (ClientConfig         *message)
{
  static const ClientConfig init_value = CLIENT_CONFIG__INIT;
  *message = init_value;
}
size_t client_config__get_packed_size
                     (const ClientConfig *message)
{
  assert(message->base.descriptor == &client_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_config__pack
                     (const ClientConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_config__pack_to_buffer
                     (const ClientConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientConfig *
       client_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientConfig *)
     protobuf_c_message_unpack (&client_config__descriptor,
                                allocator, len, data);
}
void   client_config__free_unpacked
                     (ClientConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cover_config__init
                     (CoverConfig         *message)
{
  static const CoverConfig init_value = COVER_CONFIG__INIT;
  *message = init_value;
}
size_t cover_config__get_packed_size
                     (const CoverConfig *message)
{
  assert(message->base.descriptor == &cover_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cover_config__pack
                     (const CoverConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cover_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cover_config__pack_to_buffer
                     (const CoverConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cover_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CoverConfig *
       cover_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CoverConfig *)
     protobuf_c_message_unpack (&cover_config__descriptor,
                                allocator, len, data);
}
void   cover_config__free_unpacked
                     (CoverConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cover_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_msg__init
                     (LoginMsg         *message)
{
  static const LoginMsg init_value = LOGIN_MSG__INIT;
  *message = init_value;
}
size_t login_msg__get_packed_size
                     (const LoginMsg *message)
{
  assert(message->base.descriptor == &login_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_msg__pack
                     (const LoginMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_msg__pack_to_buffer
                     (const LoginMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginMsg *
       login_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginMsg *)
     protobuf_c_message_unpack (&login_msg__descriptor,
                                allocator, len, data);
}
void   login_msg__free_unpacked
                     (LoginMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   base_nonce_exchange__init
                     (BaseNonceExchange         *message)
{
  static const BaseNonceExchange init_value = BASE_NONCE_EXCHANGE__INIT;
  *message = init_value;
}
size_t base_nonce_exchange__get_packed_size
                     (const BaseNonceExchange *message)
{
  assert(message->base.descriptor == &base_nonce_exchange__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t base_nonce_exchange__pack
                     (const BaseNonceExchange *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &base_nonce_exchange__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t base_nonce_exchange__pack_to_buffer
                     (const BaseNonceExchange *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &base_nonce_exchange__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BaseNonceExchange *
       base_nonce_exchange__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BaseNonceExchange *)
     protobuf_c_message_unpack (&base_nonce_exchange__descriptor,
                                allocator, len, data);
}
void   base_nonce_exchange__free_unpacked
                     (BaseNonceExchange *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &base_nonce_exchange__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   command_ack__init
                     (CommandAck         *message)
{
  static const CommandAck init_value = COMMAND_ACK__INIT;
  *message = init_value;
}
size_t command_ack__get_packed_size
                     (const CommandAck *message)
{
  assert(message->base.descriptor == &command_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command_ack__pack
                     (const CommandAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command_ack__pack_to_buffer
                     (const CommandAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CommandAck *
       command_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CommandAck *)
     protobuf_c_message_unpack (&command_ack__descriptor,
                                allocator, len, data);
}
void   command_ack__free_unpacked
                     (CommandAck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &command_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   encrypted_payload__init
                     (EncryptedPayload         *message)
{
  static const EncryptedPayload init_value = ENCRYPTED_PAYLOAD__INIT;
  *message = init_value;
}
size_t encrypted_payload__get_packed_size
                     (const EncryptedPayload *message)
{
  assert(message->base.descriptor == &encrypted_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t encrypted_payload__pack
                     (const EncryptedPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &encrypted_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t encrypted_payload__pack_to_buffer
                     (const EncryptedPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &encrypted_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EncryptedPayload *
       encrypted_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EncryptedPayload *)
     protobuf_c_message_unpack (&encrypted_payload__descriptor,
                                allocator, len, data);
}
void   encrypted_payload__free_unpacked
                     (EncryptedPayload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &encrypted_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   time_sync__init
                     (TimeSync         *message)
{
  static const TimeSync init_value = TIME_SYNC__INIT;
  *message = init_value;
}
size_t time_sync__get_packed_size
                     (const TimeSync *message)
{
  assert(message->base.descriptor == &time_sync__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_sync__pack
                     (const TimeSync *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_sync__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_sync__pack_to_buffer
                     (const TimeSync *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_sync__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeSync *
       time_sync__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeSync *)
     protobuf_c_message_unpack (&time_sync__descriptor,
                                allocator, len, data);
}
void   time_sync__free_unpacked
                     (TimeSync *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &time_sync__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   schedule_entry__init
                     (ScheduleEntry         *message)
{
  static const ScheduleEntry init_value = SCHEDULE_ENTRY__INIT;
  *message = init_value;
}
size_t schedule_entry__get_packed_size
                     (const ScheduleEntry *message)
{
  assert(message->base.descriptor == &schedule_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t schedule_entry__pack
                     (const ScheduleEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &schedule_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t schedule_entry__pack_to_buffer
                     (const ScheduleEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &schedule_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScheduleEntry *
       schedule_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScheduleEntry *)
     protobuf_c_message_unpack (&schedule_entry__descriptor,
                                allocator, len, data);
}
void   schedule_entry__free_unpacked
                     (ScheduleEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &schedule_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   schedule_config__init
                     (ScheduleConfig         *message)
{
  static const ScheduleConfig init_value = SCHEDULE_CONFIG__INIT;
  *message = init_value;
}
size_t schedule_config__get_packed_size
                     (const ScheduleConfig *message)
{
  assert(message->base.descriptor == &schedule_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t schedule_config__pack
                     (const ScheduleConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &schedule_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t schedule_config__pack_to_buffer
                     (const ScheduleConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &schedule_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScheduleConfig *
       schedule_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScheduleConfig *)
     protobuf_c_message_unpack (&schedule_config__descriptor,
                                allocator, len, data);
}
void   schedule_config__free_unpacked
                     (ScheduleConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &schedule_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   node_wake_beacon__init
                     (NodeWakeBeacon         *message)
{
  static const NodeWakeBeacon init_value = NODE_WAKE_BEACON__INIT;
  *message = init_value;
}
size_t node_wake_beacon__get_packed_size
                     (const NodeWakeBeacon *message)
{
  assert(message->base.descriptor == &node_wake_beacon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node_wake_beacon__pack
                     (const NodeWakeBeacon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node_wake_beacon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node_wake_beacon__pack_to_buffer
                     (const NodeWakeBeacon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node_wake_beacon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NodeWakeBeacon *
       node_wake_beacon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NodeWakeBeacon *)
     protobuf_c_message_unpack (&node_wake_beacon__descriptor,
                                allocator, len, data);
}
void   node_wake_beacon__free_unpacked
                     (NodeWakeBeacon *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node_wake_beacon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora_header__init
                     (LoraHeader         *message)
{
  static const LoraHeader init_value = LORA_HEADER__INIT;
  *message = init_value;
}
size_t lora_header__get_packed_size
                     (const LoraHeader *message)
{
  assert(message->base.descriptor == &lora_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora_header__pack
                     (const LoraHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora_header__pack_to_buffer
                     (const LoraHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoraHeader *
       lora_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoraHeader *)
     protobuf_c_message_unpack (&lora_header__descriptor,
                                allocator, len, data);
}
void   lora_header__free_unpacked
                     (LoraHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drift_test__init
                     (DriftTest         *message)
{
  static const DriftTest init_value = DRIFT_TEST__INIT;
  *message = init_value;
}
size_t drift_test__get_packed_size
                     (const DriftTest *message)
{
  assert(message->base.descriptor == &drift_test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drift_test__pack
                     (const DriftTest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drift_test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drift_test__pack_to_buffer
                     (const DriftTest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drift_test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DriftTest *
       drift_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DriftTest *)
     protobuf_c_message_unpack (&drift_test__descriptor,
                                allocator, len, data);
}
void   drift_test__free_unpacked
                     (DriftTest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &drift_test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora_client_operation_message__init
                     (LoraClientOperationMessage         *message)
{
  static const LoraClientOperationMessage init_value = LORA_CLIENT_OPERATION_MESSAGE__INIT;
  *message = init_value;
}
size_t lora_client_operation_message__get_packed_size
                     (const LoraClientOperationMessage *message)
{
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora_client_operation_message__pack
                     (const LoraClientOperationMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora_client_operation_message__pack_to_buffer
                     (const LoraClientOperationMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoraClientOperationMessage *
       lora_client_operation_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoraClientOperationMessage *)
     protobuf_c_message_unpack (&lora_client_operation_message__descriptor,
                                allocator, len, data);
}
void   lora_client_operation_message__free_unpacked
                     (LoraClientOperationMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora_client_operation_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_register__init
                     (ClientRegister         *message)
{
  static const ClientRegister init_value = CLIENT_REGISTER__INIT;
  *message = init_value;
}
size_t client_register__get_packed_size
                     (const ClientRegister *message)
{
  assert(message->base.descriptor == &client_register__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_register__pack
                     (const ClientRegister *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_register__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_register__pack_to_buffer
                     (const ClientRegister *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_register__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientRegister *
       client_register__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientRegister *)
     protobuf_c_message_unpack (&client_register__descriptor,
                                allocator, len, data);
}
void   client_register__free_unpacked
                     (ClientRegister *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_register__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_available__init
                     (ClientAvailable         *message)
{
  static const ClientAvailable init_value = CLIENT_AVAILABLE__INIT;
  *message = init_value;
}
size_t client_available__get_packed_size
                     (const ClientAvailable *message)
{
  assert(message->base.descriptor == &client_available__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_available__pack
                     (const ClientAvailable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_available__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_available__pack_to_buffer
                     (const ClientAvailable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_available__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientAvailable *
       client_available__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientAvailable *)
     protobuf_c_message_unpack (&client_available__descriptor,
                                allocator, len, data);
}
void   client_available__free_unpacked
                     (ClientAvailable *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_available__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_battery__init
                     (ClientBattery         *message)
{
  static const ClientBattery init_value = CLIENT_BATTERY__INIT;
  *message = init_value;
}
size_t client_battery__get_packed_size
                     (const ClientBattery *message)
{
  assert(message->base.descriptor == &client_battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_battery__pack
                     (const ClientBattery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client_battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_battery__pack_to_buffer
                     (const ClientBattery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client_battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientBattery *
       client_battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientBattery *)
     protobuf_c_message_unpack (&client_battery__descriptor,
                                allocator, len, data);
}
void   client_battery__free_unpacked
                     (ClientBattery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client_battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cover_position__init
                     (CoverPosition         *message)
{
  static const CoverPosition init_value = COVER_POSITION__INIT;
  *message = init_value;
}
size_t cover_position__get_packed_size
                     (const CoverPosition *message)
{
  assert(message->base.descriptor == &cover_position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cover_position__pack
                     (const CoverPosition *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cover_position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cover_position__pack_to_buffer
                     (const CoverPosition *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cover_position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CoverPosition *
       cover_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CoverPosition *)
     protobuf_c_message_unpack (&cover_position__descriptor,
                                allocator, len, data);
}
void   cover_position__free_unpacked
                     (CoverPosition *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cover_position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lora_client_response_message__init
                     (LoraClientResponseMessage         *message)
{
  static const LoraClientResponseMessage init_value = LORA_CLIENT_RESPONSE_MESSAGE__INIT;
  *message = init_value;
}
size_t lora_client_response_message__get_packed_size
                     (const LoraClientResponseMessage *message)
{
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lora_client_response_message__pack
                     (const LoraClientResponseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lora_client_response_message__pack_to_buffer
                     (const LoraClientResponseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoraClientResponseMessage *
       lora_client_response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoraClientResponseMessage *)
     protobuf_c_message_unpack (&lora_client_response_message__descriptor,
                                allocator, len, data);
}
void   lora_client_response_message__free_unpacked
                     (LoraClientResponseMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lora_client_response_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lora_cover_operation__field_descriptors[2] =
{
  {
    "operation",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(LoraCoverOperation, covop_case),
    offsetof(LoraCoverOperation, operation),
    &cov_operation__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(LoraCoverOperation, covop_case),
    offsetof(LoraCoverOperation, position),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora_cover_operation__field_indices_by_name[] = {
  0,   /* field[0] = operation */
  1,   /* field[1] = position */
};
static const ProtobufCIntRange lora_cover_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lora_cover_operation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoraCoverOperation",
  "LoraCoverOperation",
  "LoraCoverOperation",
  "",
  sizeof(LoraCoverOperation),
  2,
  lora_cover_operation__field_descriptors,
  lora_cover_operation__field_indices_by_name,
  1,  lora_cover_operation__number_ranges,
  (ProtobufCMessageInit) lora_cover_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_config__field_descriptors[6] =
{
  {
    "mac_addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, mac_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subnt",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, subnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sleepDuration",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, sleepduration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "batteryInterval",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ClientConfig, batteryinterval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_config__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  5,   /* field[5] = batteryInterval */
  0,   /* field[0] = mac_addr */
  3,   /* field[3] = name */
  4,   /* field[4] = sleepDuration */
  2,   /* field[2] = subnt */
};
static const ProtobufCIntRange client_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor client_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientConfig",
  "ClientConfig",
  "ClientConfig",
  "",
  sizeof(ClientConfig),
  6,
  client_config__field_descriptors,
  client_config__field_indices_by_name,
  1,  client_config__number_ranges,
  (ProtobufCMessageInit) client_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cover_config__field_descriptors[7] =
{
  {
    "openTime",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, opentime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeTime",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, closetime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blindHeightMm",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, blindheightmm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "axleDiameterMm",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, axlediametermm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blindThicknessMm",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, blindthicknessmm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "openSlack",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, openslack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeSlack",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CoverConfig, closeslack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cover_config__field_indices_by_name[] = {
  3,   /* field[3] = axleDiameterMm */
  2,   /* field[2] = blindHeightMm */
  4,   /* field[4] = blindThicknessMm */
  6,   /* field[6] = closeSlack */
  1,   /* field[1] = closeTime */
  5,   /* field[5] = openSlack */
  0,   /* field[0] = openTime */
};
static const ProtobufCIntRange cover_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cover_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CoverConfig",
  "CoverConfig",
  "CoverConfig",
  "",
  sizeof(CoverConfig),
  7,
  cover_config__field_descriptors,
  cover_config__field_indices_by_name,
  1,  cover_config__number_ranges,
  (ProtobufCMessageInit) cover_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_msg__field_descriptors[2] =
{
  {
    "nonce",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoginMsg, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_register",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LoginMsg, request_register),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_msg__field_indices_by_name[] = {
  0,   /* field[0] = nonce */
  1,   /* field[1] = request_register */
};
static const ProtobufCIntRange login_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginMsg",
  "LoginMsg",
  "LoginMsg",
  "",
  sizeof(LoginMsg),
  2,
  login_msg__field_descriptors,
  login_msg__field_indices_by_name,
  1,  login_msg__number_ranges,
  (ProtobufCMessageInit) login_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor base_nonce_exchange__field_descriptors[2] =
{
  {
    "key_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BaseNonceExchange, key_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_nonce",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BaseNonceExchange, base_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned base_nonce_exchange__field_indices_by_name[] = {
  1,   /* field[1] = base_nonce */
  0,   /* field[0] = key_id */
};
static const ProtobufCIntRange base_nonce_exchange__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor base_nonce_exchange__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BaseNonceExchange",
  "BaseNonceExchange",
  "BaseNonceExchange",
  "",
  sizeof(BaseNonceExchange),
  2,
  base_nonce_exchange__field_descriptors,
  base_nonce_exchange__field_indices_by_name,
  1,  base_nonce_exchange__number_ranges,
  (ProtobufCMessageInit) base_nonce_exchange__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor command_ack__field_descriptors[2] =
{
  {
    "ack_msg_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CommandAck, ack_msg_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CommandAck, status),
    &ack_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command_ack__field_indices_by_name[] = {
  0,   /* field[0] = ack_msg_id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange command_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor command_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CommandAck",
  "CommandAck",
  "CommandAck",
  "",
  sizeof(CommandAck),
  2,
  command_ack__field_descriptors,
  command_ack__field_indices_by_name,
  1,  command_ack__number_ranges,
  (ProtobufCMessageInit) command_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor encrypted_payload__field_descriptors[2] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EncryptedPayload, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ciphertext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(EncryptedPayload, ciphertext),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned encrypted_payload__field_indices_by_name[] = {
  1,   /* field[1] = ciphertext */
  0,   /* field[0] = tag */
};
static const ProtobufCIntRange encrypted_payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor encrypted_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EncryptedPayload",
  "EncryptedPayload",
  "EncryptedPayload",
  "",
  sizeof(EncryptedPayload),
  2,
  encrypted_payload__field_descriptors,
  encrypted_payload__field_indices_by_name,
  1,  encrypted_payload__number_ranges,
  (ProtobufCMessageInit) encrypted_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor time_sync__field_descriptors[4] =
{
  {
    "epoch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TimeSync, epoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "utcOffset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TimeSync, utcoffset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dstNext",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TimeSync, dstnext),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sleepOk",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(TimeSync, sleepok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_sync__field_indices_by_name[] = {
  2,   /* field[2] = dstNext */
  0,   /* field[0] = epoch */
  3,   /* field[3] = sleepOk */
  1,   /* field[1] = utcOffset */
};
static const ProtobufCIntRange time_sync__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor time_sync__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeSync",
  "TimeSync",
  "TimeSync",
  "",
  sizeof(TimeSync),
  4,
  time_sync__field_descriptors,
  time_sync__field_indices_by_name,
  1,  time_sync__number_ranges,
  (ProtobufCMessageInit) time_sync__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor schedule_entry__field_descriptors[5] =
{
  {
    "minuteOfDay",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleEntry, minuteofday),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dayMask",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleEntry, daymask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ScheduleEntry, action),
    &sched_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "positionPct",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleEntry, positionpct),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kind",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleEntry, kind),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned schedule_entry__field_indices_by_name[] = {
  2,   /* field[2] = action */
  1,   /* field[1] = dayMask */
  4,   /* field[4] = kind */
  0,   /* field[0] = minuteOfDay */
  3,   /* field[3] = positionPct */
};
static const ProtobufCIntRange schedule_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor schedule_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScheduleEntry",
  "ScheduleEntry",
  "ScheduleEntry",
  "",
  sizeof(ScheduleEntry),
  5,
  schedule_entry__field_descriptors,
  schedule_entry__field_indices_by_name,
  1,  schedule_entry__number_ranges,
  (ProtobufCMessageInit) schedule_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor schedule_config__field_descriptors[8] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleConfig, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ScheduleConfig, mode),
    &node_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interactiveTimeout_s",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleConfig, interactivetimeout_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "checkinInterval_s",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleConfig, checkininterval_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beaconLead_s",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleConfig, beaconlead_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "postEventWindow_s",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleConfig, posteventwindow_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "catchupWindow_s",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ScheduleConfig, catchupwindow_s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScheduleConfig, n_entries),
    offsetof(ScheduleConfig, entries),
    &schedule_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned schedule_config__field_indices_by_name[] = {
  4,   /* field[4] = beaconLead_s */
  6,   /* field[6] = catchupWindow_s */
  3,   /* field[3] = checkinInterval_s */
  7,   /* field[7] = entries */
  2,   /* field[2] = interactiveTimeout_s */
  1,   /* field[1] = mode */
  5,   /* field[5] = postEventWindow_s */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange schedule_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor schedule_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScheduleConfig",
  "ScheduleConfig",
  "ScheduleConfig",
  "",
  sizeof(ScheduleConfig),
  8,
  schedule_config__field_descriptors,
  schedule_config__field_indices_by_name,
  1,  schedule_config__number_ranges,
  (ProtobufCMessageInit) schedule_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor node_wake_beacon__field_descriptors[12] =
{
  {
    "reason",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, reason),
    &wake_reason__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schedVersion",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, schedversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodeEpoch",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, nodeepoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, mode),
    &node_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "awakeWindow_ms",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, awakewindow_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nextEventEpoch",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, nexteventepoch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sessionResume",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, sessionresume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clockValid",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, clockvalid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fwVersion",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, fwversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resetReason",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(NodeWakeBeacon, resetreason),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node_wake_beacon__field_indices_by_name[] = {
  6,   /* field[6] = awakeWindow_ms */
  9,   /* field[9] = clockValid */
  10,   /* field[10] = fwVersion */
  3,   /* field[3] = mode */
  7,   /* field[7] = nextEventEpoch */
  2,   /* field[2] = nodeEpoch */
  5,   /* field[5] = position */
  0,   /* field[0] = reason */
  11,   /* field[11] = resetReason */
  1,   /* field[1] = schedVersion */
  8,   /* field[8] = sessionResume */
  4,   /* field[4] = voltage */
};
static const ProtobufCIntRange node_wake_beacon__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor node_wake_beacon__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NodeWakeBeacon",
  "NodeWakeBeacon",
  "NodeWakeBeacon",
  "",
  sizeof(NodeWakeBeacon),
  12,
  node_wake_beacon__field_descriptors,
  node_wake_beacon__field_indices_by_name,
  1,  node_wake_beacon__number_ranges,
  (ProtobufCMessageInit) node_wake_beacon__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora_header__field_descriptors[6] =
{
  {
    "destAddress",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraHeader, destaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destSubnet",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraHeader, destsubnet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "senderAddress",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraHeader, senderaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraHeader, msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burstIndex",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraHeader, burstindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "burstCount",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(LoraHeader, burstcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora_header__field_indices_by_name[] = {
  5,   /* field[5] = burstCount */
  4,   /* field[4] = burstIndex */
  0,   /* field[0] = destAddress */
  1,   /* field[1] = destSubnet */
  3,   /* field[3] = msgId */
  2,   /* field[2] = senderAddress */
};
static const ProtobufCIntRange lora_header__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor lora_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoraHeader",
  "LoraHeader",
  "LoraHeader",
  "",
  sizeof(LoraHeader),
  6,
  lora_header__field_descriptors,
  lora_header__field_indices_by_name,
  2,  lora_header__number_ranges,
  (ProtobufCMessageInit) lora_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drift_test__field_descriptors[3] =
{
  {
    "enable",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DriftTest, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "durationS",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DriftTest, durations),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gridPeriodMs",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DriftTest, gridperiodms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drift_test__field_indices_by_name[] = {
  1,   /* field[1] = durationS */
  0,   /* field[0] = enable */
  2,   /* field[2] = gridPeriodMs */
};
static const ProtobufCIntRange drift_test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drift_test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DriftTest",
  "DriftTest",
  "DriftTest",
  "",
  sizeof(DriftTest),
  3,
  drift_test__field_descriptors,
  drift_test__field_indices_by_name,
  1,  drift_test__number_ranges,
  (ProtobufCMessageInit) drift_test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora_client_operation_message__field_descriptors[11] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LoraClientOperationMessage, header),
    &lora_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, encrypted),
    &encrypted_payload__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operation",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, operation),
    &lora_cover_operation__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sysop",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, sysop),
    &client_operation__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientconfig",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, clientconfig),
    &client_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coverconfig",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, coverconfig),
    &cover_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "login",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, login),
    &login_msg__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "basenonce",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, basenonce),
    &base_nonce_exchange__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timesync",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, timesync),
    &time_sync__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schedule",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, schedule),
    &schedule_config__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drifttest",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientOperationMessage, cmd_case),
    offsetof(LoraClientOperationMessage, drifttest),
    &drift_test__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora_client_operation_message__field_indices_by_name[] = {
  7,   /* field[7] = basenonce */
  4,   /* field[4] = clientconfig */
  5,   /* field[5] = coverconfig */
  10,   /* field[10] = drifttest */
  1,   /* field[1] = encrypted */
  0,   /* field[0] = header */
  6,   /* field[6] = login */
  2,   /* field[2] = operation */
  9,   /* field[9] = schedule */
  3,   /* field[3] = sysop */
  8,   /* field[8] = timesync */
};
static const ProtobufCIntRange lora_client_operation_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 1 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor lora_client_operation_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoraClientOperationMessage",
  "LoraClientOperationMessage",
  "LoraClientOperationMessage",
  "",
  sizeof(LoraClientOperationMessage),
  11,
  lora_client_operation_message__field_descriptors,
  lora_client_operation_message__field_indices_by_name,
  2,  lora_client_operation_message__number_ranges,
  (ProtobufCMessageInit) lora_client_operation_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_register__field_descriptors[2] =
{
  {
    "mac_addr",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ClientRegister, mac_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "needs_config",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientRegister, needs_config),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_register__field_indices_by_name[] = {
  0,   /* field[0] = mac_addr */
  1,   /* field[1] = needs_config */
};
static const ProtobufCIntRange client_register__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor client_register__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientRegister",
  "ClientRegister",
  "ClientRegister",
  "",
  sizeof(ClientRegister),
  2,
  client_register__field_descriptors,
  client_register__field_indices_by_name,
  1,  client_register__number_ranges,
  (ProtobufCMessageInit) client_register__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_available__field_descriptors[1] =
{
  {
    "available",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ClientAvailable, available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_available__field_indices_by_name[] = {
  0,   /* field[0] = available */
};
static const ProtobufCIntRange client_available__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_available__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientAvailable",
  "ClientAvailable",
  "ClientAvailable",
  "",
  sizeof(ClientAvailable),
  1,
  client_available__field_descriptors,
  client_available__field_indices_by_name,
  1,  client_available__number_ranges,
  (ProtobufCMessageInit) client_available__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_battery__field_descriptors[1] =
{
  {
    "voltage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ClientBattery, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_battery__field_indices_by_name[] = {
  0,   /* field[0] = voltage */
};
static const ProtobufCIntRange client_battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ClientBattery",
  "ClientBattery",
  "ClientBattery",
  "",
  sizeof(ClientBattery),
  1,
  client_battery__field_descriptors,
  client_battery__field_indices_by_name,
  1,  client_battery__number_ranges,
  (ProtobufCMessageInit) client_battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cover_position__field_descriptors[3] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CoverPosition, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CoverPosition, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CoverPosition, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cover_position__field_indices_by_name[] = {
  2,   /* field[2] = current */
  0,   /* field[0] = position */
  1,   /* field[1] = voltage */
};
static const ProtobufCIntRange cover_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cover_position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CoverPosition",
  "CoverPosition",
  "CoverPosition",
  "",
  sizeof(CoverPosition),
  3,
  cover_position__field_descriptors,
  cover_position__field_indices_by_name,
  1,  cover_position__number_ranges,
  (ProtobufCMessageInit) cover_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lora_client_response_message__field_descriptors[9] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(LoraClientResponseMessage, header),
    &lora_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, encrypted),
    &encrypted_payload__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, avail),
    &client_available__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, register_),
    &client_register__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, state),
    &client_battery__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, position),
    &cover_position__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "login",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, login),
    &login_msg__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, ack),
    &command_ack__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beacon",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LoraClientResponseMessage, proto_case),
    offsetof(LoraClientResponseMessage, beacon),
    &node_wake_beacon__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lora_client_response_message__field_indices_by_name[] = {
  7,   /* field[7] = ack */
  2,   /* field[2] = avail */
  8,   /* field[8] = beacon */
  1,   /* field[1] = encrypted */
  0,   /* field[0] = header */
  6,   /* field[6] = login */
  5,   /* field[5] = position */
  3,   /* field[3] = register */
  4,   /* field[4] = state */
};
static const ProtobufCIntRange lora_client_response_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 1 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lora_client_response_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoraClientResponseMessage",
  "LoraClientResponseMessage",
  "LoraClientResponseMessage",
  "",
  sizeof(LoraClientResponseMessage),
  9,
  lora_client_response_message__field_descriptors,
  lora_client_response_message__field_indices_by_name,
  2,  lora_client_response_message__number_ranges,
  (ProtobufCMessageInit) lora_client_response_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cov_operation__enum_values_by_number[3] =
{
  { "CMD_OPEN", "COV_OPERATION__CMD_OPEN", 0 },
  { "CMD_CLOSE", "COV_OPERATION__CMD_CLOSE", 1 },
  { "CMD_STOP", "COV_OPERATION__CMD_STOP", 2 },
};
static const ProtobufCIntRange cov_operation__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex cov_operation__enum_values_by_name[3] =
{
  { "CMD_CLOSE", 1 },
  { "CMD_OPEN", 0 },
  { "CMD_STOP", 2 },
};
const ProtobufCEnumDescriptor cov_operation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CovOperation",
  "CovOperation",
  "CovOperation",
  "",
  3,
  cov_operation__enum_values_by_number,
  3,
  cov_operation__enum_values_by_name,
  1,
  cov_operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_operation__enum_values_by_number[7] =
{
  { "CMD_ENABLE_WIFI", "CLIENT_OPERATION__CMD_ENABLE_WIFI", 0 },
  { "CMD_DISABLE_WIFI", "CLIENT_OPERATION__CMD_DISABLE_WIFI", 1 },
  { "CMD_OTA", "CLIENT_OPERATION__CMD_OTA", 2 },
  { "CMD_STATUS", "CLIENT_OPERATION__CMD_STATUS", 3 },
  { "CMD_SLEEP", "CLIENT_OPERATION__CMD_SLEEP", 4 },
  { "CMD_MODE_AUTO", "CLIENT_OPERATION__CMD_MODE_AUTO", 5 },
  { "CMD_MODE_INTERACTIVE", "CLIENT_OPERATION__CMD_MODE_INTERACTIVE", 6 },
};
static const ProtobufCIntRange client_operation__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex client_operation__enum_values_by_name[7] =
{
  { "CMD_DISABLE_WIFI", 1 },
  { "CMD_ENABLE_WIFI", 0 },
  { "CMD_MODE_AUTO", 5 },
  { "CMD_MODE_INTERACTIVE", 6 },
  { "CMD_OTA", 2 },
  { "CMD_SLEEP", 4 },
  { "CMD_STATUS", 3 },
};
const ProtobufCEnumDescriptor client_operation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientOperation",
  "ClientOperation",
  "ClientOperation",
  "",
  7,
  client_operation__enum_values_by_number,
  7,
  client_operation__enum_values_by_name,
  1,
  client_operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue encryption_algo__enum_values_by_number[2] =
{
  { "ENC_NONE", "ENCRYPTION_ALGO__ENC_NONE", 0 },
  { "ENC_AES_GCM_128", "ENCRYPTION_ALGO__ENC_AES_GCM_128", 1 },
};
static const ProtobufCIntRange encryption_algo__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex encryption_algo__enum_values_by_name[2] =
{
  { "ENC_AES_GCM_128", 1 },
  { "ENC_NONE", 0 },
};
const ProtobufCEnumDescriptor encryption_algo__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EncryptionAlgo",
  "EncryptionAlgo",
  "EncryptionAlgo",
  "",
  2,
  encryption_algo__enum_values_by_number,
  2,
  encryption_algo__enum_values_by_name,
  1,
  encryption_algo__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ack_status__enum_values_by_number[3] =
{
  { "ACK_OK", "ACK_STATUS__ACK_OK", 0 },
  { "ACK_ERROR", "ACK_STATUS__ACK_ERROR", 1 },
  { "ACK_BUSY", "ACK_STATUS__ACK_BUSY", 2 },
};
static const ProtobufCIntRange ack_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex ack_status__enum_values_by_name[3] =
{
  { "ACK_BUSY", 2 },
  { "ACK_ERROR", 1 },
  { "ACK_OK", 0 },
};
const ProtobufCEnumDescriptor ack_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AckStatus",
  "AckStatus",
  "AckStatus",
  "",
  3,
  ack_status__enum_values_by_number,
  3,
  ack_status__enum_values_by_name,
  1,
  ack_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue sched_action__enum_values_by_number[4] =
{
  { "SCHED_OPEN", "SCHED_ACTION__SCHED_OPEN", 0 },
  { "SCHED_CLOSE", "SCHED_ACTION__SCHED_CLOSE", 1 },
  { "SCHED_STOP", "SCHED_ACTION__SCHED_STOP", 2 },
  { "SCHED_POSITION", "SCHED_ACTION__SCHED_POSITION", 3 },
};
static const ProtobufCIntRange sched_action__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex sched_action__enum_values_by_name[4] =
{
  { "SCHED_CLOSE", 1 },
  { "SCHED_OPEN", 0 },
  { "SCHED_POSITION", 3 },
  { "SCHED_STOP", 2 },
};
const ProtobufCEnumDescriptor sched_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SchedAction",
  "SchedAction",
  "SchedAction",
  "",
  4,
  sched_action__enum_values_by_number,
  4,
  sched_action__enum_values_by_name,
  1,
  sched_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue node_mode__enum_values_by_number[2] =
{
  { "MODE_INTERACTIVE", "NODE_MODE__MODE_INTERACTIVE", 0 },
  { "MODE_AUTO", "NODE_MODE__MODE_AUTO", 1 },
};
static const ProtobufCIntRange node_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex node_mode__enum_values_by_name[2] =
{
  { "MODE_AUTO", 1 },
  { "MODE_INTERACTIVE", 0 },
};
const ProtobufCEnumDescriptor node_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NodeMode",
  "NodeMode",
  "NodeMode",
  "",
  2,
  node_mode__enum_values_by_number,
  2,
  node_mode__enum_values_by_name,
  1,
  node_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue wake_reason__enum_values_by_number[5] =
{
  { "WAKE_BOOT", "WAKE_REASON__WAKE_BOOT", 0 },
  { "WAKE_TIMER_EVENT", "WAKE_REASON__WAKE_TIMER_EVENT", 1 },
  { "WAKE_TIMER_CHECKIN", "WAKE_REASON__WAKE_TIMER_CHECKIN", 2 },
  { "WAKE_BUTTON", "WAKE_REASON__WAKE_BUTTON", 3 },
  { "WAKE_UNKNOWN", "WAKE_REASON__WAKE_UNKNOWN", 4 },
};
static const ProtobufCIntRange wake_reason__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex wake_reason__enum_values_by_name[5] =
{
  { "WAKE_BOOT", 0 },
  { "WAKE_BUTTON", 3 },
  { "WAKE_TIMER_CHECKIN", 2 },
  { "WAKE_TIMER_EVENT", 1 },
  { "WAKE_UNKNOWN", 4 },
};
const ProtobufCEnumDescriptor wake_reason__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "WakeReason",
  "WakeReason",
  "WakeReason",
  "",
  5,
  wake_reason__enum_values_by_number,
  5,
  wake_reason__enum_values_by_name,
  1,
  wake_reason__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
