/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: blinds.proto */

#ifndef PROTOBUF_C_blinds_2eproto__INCLUDED
#define PROTOBUF_C_blinds_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct LoraCoverOperation LoraCoverOperation;
typedef struct ClientConfig ClientConfig;
typedef struct CoverConfig CoverConfig;
typedef struct LoginMsg LoginMsg;
typedef struct BaseNonceExchange BaseNonceExchange;
typedef struct CommandAck CommandAck;
typedef struct EncryptedPayload EncryptedPayload;
typedef struct LoraHeader LoraHeader;
typedef struct LoraClientOperationMessage LoraClientOperationMessage;
typedef struct ClientRegister ClientRegister;
typedef struct ClientAvailable ClientAvailable;
typedef struct ClientBattery ClientBattery;
typedef struct CoverPosition CoverPosition;
typedef struct LoraClientResponseMessage LoraClientResponseMessage;


/* --- enums --- */

typedef enum _CovOperation {
  COV_OPERATION__CMD_OPEN = 0,
  COV_OPERATION__CMD_CLOSE = 1,
  COV_OPERATION__CMD_STOP = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COV_OPERATION)
} CovOperation;
typedef enum _ClientOperation {
  CLIENT_OPERATION__CMD_ENABLE_WIFI = 0,
  CLIENT_OPERATION__CMD_DISABLE_WIFI = 1,
  CLIENT_OPERATION__CMD_OTA = 2,
  CLIENT_OPERATION__CMD_STATUS = 3,
  CLIENT_OPERATION__CMD_SLEEP = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLIENT_OPERATION)
} ClientOperation;
/*
 * Encryption algorithm identifiers for on-air encrypted payloads.
 */
typedef enum _EncryptionAlgo {
  ENCRYPTION_ALGO__ENC_NONE = 0,
  /*
   * AES-GCM 128-bit key (recommended)
   */
  ENCRYPTION_ALGO__ENC_AES_GCM_128 = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ENCRYPTION_ALGO)
} EncryptionAlgo;
/*
 * Result of processing a command on the node.
 */
typedef enum _AckStatus {
  /*
   * command accepted / executed
   */
  ACK_STATUS__ACK_OK = 0,
  /*
   * command rejected or failed
   */
  ACK_STATUS__ACK_ERROR = 1,
  /*
   * node busy, command not applied
   */
  ACK_STATUS__ACK_BUSY = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ACK_STATUS)
} AckStatus;

/* --- messages --- */

typedef enum {
  LORA_COVER_OPERATION__COVOP__NOT_SET = 0,
  LORA_COVER_OPERATION__COVOP_OPERATION = 1,
  LORA_COVER_OPERATION__COVOP_POSITION = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA_COVER_OPERATION__COVOP__CASE)
} LoraCoverOperation__CovopCase;

struct  LoraCoverOperation
{
  ProtobufCMessage base;
  LoraCoverOperation__CovopCase covop_case;
  union {
    float position;
    CovOperation operation;
  };
};
#define LORA_COVER_OPERATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora_cover_operation__descriptor) \
    , LORA_COVER_OPERATION__COVOP__NOT_SET, {0} }


struct  ClientConfig
{
  ProtobufCMessage base;
  uint64_t mac_addr;
  uint32_t addr;
  uint32_t subnt;
  ProtobufCBinaryData name;
  uint64_t sleepduration;
};
#define CLIENT_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_config__descriptor) \
    , 0, 0, 0, {0,NULL}, 0 }


struct  CoverConfig
{
  ProtobufCMessage base;
  uint32_t opentime;
  uint32_t closetime;
  float blindheightmm;
  float axlediametermm;
  float blindthicknessmm;
  /*
   * Slat-slack handling at the bottom (closed) end.  openTime/closeTime are the
   * bar-TRAVEL-only times (top <-> sill).  These add the extra motor run at the
   * sill where the bar is parked and the slats nest/un-nest:
   *   openSlack  = un-seal time: motor runs UP with position pinned at 0 before
   *                travel starts, when opening FROM the fully-sealed state.
   *   closeSlack = seal time: extra run budget after travel reaches 0 on a full
   *                close, so the timed backstop does not cut the compression.
   * Both in seconds; 0 = disabled (legacy behaviour).
   */
  uint32_t openslack;
  uint32_t closeslack;
};
#define COVER_CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cover_config__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0 }


struct  LoginMsg
{
  ProtobufCMessage base;
  uint32_t nonce;
};
#define LOGIN_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&login_msg__descriptor) \
    , 0 }


/*
 * Exchange used to provision a per-peer base nonce for nonce derivation.
 */
struct  BaseNonceExchange
{
  ProtobufCMessage base;
  /*
   * Optional key identifier for which key this base-nonce is associated
   */
  ProtobufCBinaryData key_id;
  /*
   * 4-byte base nonce unique per-peer
   */
  ProtobufCBinaryData base_nonce;
};
#define BASE_NONCE_EXCHANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&base_nonce_exchange__descriptor) \
    , {0,NULL}, {0,NULL} }


/*
 * Acknowledgement of a received command, sent node -> hub so the hub can
 * confirm delivery and stop retransmitting.  ack_msg_id echoes the
 * LoraHeader.msgId of the command being acknowledged.
 */
struct  CommandAck
{
  ProtobufCMessage base;
  uint32_t ack_msg_id;
  AckStatus status;
};
#define COMMAND_ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&command_ack__descriptor) \
    , 0, ACK_STATUS__ACK_OK }


/*
 * When a payload is encrypted, the structured protobuf messages are not
 * present; instead the envelope carries this EncryptedPayload which holds
 * algorithm metadata, IV, optional key identifier, auth tag and ciphertext.
 * Slim on-air AEAD envelope.  Algorithm is fixed (AES-GCM-128 with a truncated
 * tag), and the IV/AAD are reconstructed by the receiver from the plaintext
 * outer header — so only the tag and ciphertext are transmitted.  The ciphertext
 * is the payload-only inner message (its header is NOT re-encrypted; the receiver
 * uses the outer header).
 */
struct  EncryptedPayload
{
  ProtobufCMessage base;
  /*
   * truncated AES-GCM-128 auth tag
   */
  ProtobufCBinaryData tag;
  /*
   * AEAD-encrypted payload-only inner protobuf
   */
  ProtobufCBinaryData ciphertext;
};
#define ENCRYPTED_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&encrypted_payload__descriptor) \
    , {0,NULL}, {0,NULL} }


struct  LoraHeader
{
  ProtobufCMessage base;
  uint32_t destaddress;
  uint32_t destsubnet;
  uint32_t senderaddress;
  uint32_t msgid;
  /*
   * field 5 (encrypted) removed — encryption is inferred from the oneof case
   * (presence of the `encrypted` payload), not a header flag.
   * Burst scheduling (hub -> node): each copy of a TX burst carries its own
   * 0-based index and the total count.  The node uses these to compute when
   * the burst ends and defers its response until the channel is clear.
   * burstCount == 0 means "not part of a burst" (single-shot) -> no deferral.
   */
  uint32_t burstindex;
  uint32_t burstcount;
};
#define LORA_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora_header__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


typedef enum {
  LORA_CLIENT_OPERATION_MESSAGE__CMD__NOT_SET = 0,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_OPERATION = 10,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_SYSOP = 11,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_CLIENTCONFIG = 12,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_COVERCONFIG = 13,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_LOGIN = 14,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_BASENONCE = 15,
  LORA_CLIENT_OPERATION_MESSAGE__CMD_ENCRYPTED = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA_CLIENT_OPERATION_MESSAGE__CMD__CASE)
} LoraClientOperationMessage__CmdCase;

struct  LoraClientOperationMessage
{
  ProtobufCMessage base;
  LoraHeader *header;
  LoraClientOperationMessage__CmdCase cmd_case;
  union {
    BaseNonceExchange *basenonce;
    ClientConfig *clientconfig;
    CoverConfig *coverconfig;
    /*
     * When this field is present the message is encrypted (AEAD blob); the
     * structured fields above are absent.  Field 9 keeps a 1-byte tag.
     */
    EncryptedPayload *encrypted;
    LoginMsg *login;
    LoraCoverOperation *operation;
    ClientOperation sysop;
  };
};
#define LORA_CLIENT_OPERATION_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora_client_operation_message__descriptor) \
    , NULL, LORA_CLIENT_OPERATION_MESSAGE__CMD__NOT_SET, {0} }


struct  ClientRegister
{
  ProtobufCMessage base;
  uint64_t mac_addr;
  /*
   * Set by the node when it needs the hub to (re)push its configuration —
   * i.e. it is not yet provisioned.  A provisioned node waking from deep
   * sleep leaves this false so the hub skips the ClientConfig/CoverConfig
   * bursts and goes straight to the LoginMsg handshake (saves awake radio
   * time / battery).  The hub also force-pushes once per hub boot regardless,
   * so config changes flashed into the hub are always delivered.
   */
  protobuf_c_boolean needs_config;
};
#define CLIENT_REGISTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_register__descriptor) \
    , 0, 0 }


struct  ClientAvailable
{
  ProtobufCMessage base;
  protobuf_c_boolean available;
};
#define CLIENT_AVAILABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_available__descriptor) \
    , 0 }


struct  ClientBattery
{
  ProtobufCMessage base;
  float voltage;
};
#define CLIENT_BATTERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&client_battery__descriptor) \
    , 0 }


struct  CoverPosition
{
  ProtobufCMessage base;
  float position;
  float voltage;
  float current;
};
#define COVER_POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cover_position__descriptor) \
    , 0, 0, 0 }


typedef enum {
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO__NOT_SET = 0,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_AVAIL = 10,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_REGISTER = 11,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_STATE = 12,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_POSITION = 13,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_LOGIN = 14,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_ACK = 15,
  LORA_CLIENT_RESPONSE_MESSAGE__PROTO_ENCRYPTED = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORA_CLIENT_RESPONSE_MESSAGE__PROTO__CASE)
} LoraClientResponseMessage__ProtoCase;

struct  LoraClientResponseMessage
{
  ProtobufCMessage base;
  LoraHeader *header;
  LoraClientResponseMessage__ProtoCase proto_case;
  union {
    CommandAck *ack;
    ClientAvailable *avail;
    /*
     * When present the message is encrypted (AEAD blob); structured fields
     * above are absent.  Field 9 keeps a 1-byte tag.
     */
    EncryptedPayload *encrypted;
    LoginMsg *login;
    CoverPosition *position;
    ClientRegister *register_;
    ClientBattery *state;
  };
};
#define LORA_CLIENT_RESPONSE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lora_client_response_message__descriptor) \
    , NULL, LORA_CLIENT_RESPONSE_MESSAGE__PROTO__NOT_SET, {0} }


/* LoraCoverOperation methods */
void   lora_cover_operation__init
                     (LoraCoverOperation         *message);
size_t lora_cover_operation__get_packed_size
                     (const LoraCoverOperation   *message);
size_t lora_cover_operation__pack
                     (const LoraCoverOperation   *message,
                      uint8_t             *out);
size_t lora_cover_operation__pack_to_buffer
                     (const LoraCoverOperation   *message,
                      ProtobufCBuffer     *buffer);
LoraCoverOperation *
       lora_cover_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora_cover_operation__free_unpacked
                     (LoraCoverOperation *message,
                      ProtobufCAllocator *allocator);
/* ClientConfig methods */
void   client_config__init
                     (ClientConfig         *message);
size_t client_config__get_packed_size
                     (const ClientConfig   *message);
size_t client_config__pack
                     (const ClientConfig   *message,
                      uint8_t             *out);
size_t client_config__pack_to_buffer
                     (const ClientConfig   *message,
                      ProtobufCBuffer     *buffer);
ClientConfig *
       client_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_config__free_unpacked
                     (ClientConfig *message,
                      ProtobufCAllocator *allocator);
/* CoverConfig methods */
void   cover_config__init
                     (CoverConfig         *message);
size_t cover_config__get_packed_size
                     (const CoverConfig   *message);
size_t cover_config__pack
                     (const CoverConfig   *message,
                      uint8_t             *out);
size_t cover_config__pack_to_buffer
                     (const CoverConfig   *message,
                      ProtobufCBuffer     *buffer);
CoverConfig *
       cover_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cover_config__free_unpacked
                     (CoverConfig *message,
                      ProtobufCAllocator *allocator);
/* LoginMsg methods */
void   login_msg__init
                     (LoginMsg         *message);
size_t login_msg__get_packed_size
                     (const LoginMsg   *message);
size_t login_msg__pack
                     (const LoginMsg   *message,
                      uint8_t             *out);
size_t login_msg__pack_to_buffer
                     (const LoginMsg   *message,
                      ProtobufCBuffer     *buffer);
LoginMsg *
       login_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   login_msg__free_unpacked
                     (LoginMsg *message,
                      ProtobufCAllocator *allocator);
/* BaseNonceExchange methods */
void   base_nonce_exchange__init
                     (BaseNonceExchange         *message);
size_t base_nonce_exchange__get_packed_size
                     (const BaseNonceExchange   *message);
size_t base_nonce_exchange__pack
                     (const BaseNonceExchange   *message,
                      uint8_t             *out);
size_t base_nonce_exchange__pack_to_buffer
                     (const BaseNonceExchange   *message,
                      ProtobufCBuffer     *buffer);
BaseNonceExchange *
       base_nonce_exchange__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   base_nonce_exchange__free_unpacked
                     (BaseNonceExchange *message,
                      ProtobufCAllocator *allocator);
/* CommandAck methods */
void   command_ack__init
                     (CommandAck         *message);
size_t command_ack__get_packed_size
                     (const CommandAck   *message);
size_t command_ack__pack
                     (const CommandAck   *message,
                      uint8_t             *out);
size_t command_ack__pack_to_buffer
                     (const CommandAck   *message,
                      ProtobufCBuffer     *buffer);
CommandAck *
       command_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   command_ack__free_unpacked
                     (CommandAck *message,
                      ProtobufCAllocator *allocator);
/* EncryptedPayload methods */
void   encrypted_payload__init
                     (EncryptedPayload         *message);
size_t encrypted_payload__get_packed_size
                     (const EncryptedPayload   *message);
size_t encrypted_payload__pack
                     (const EncryptedPayload   *message,
                      uint8_t             *out);
size_t encrypted_payload__pack_to_buffer
                     (const EncryptedPayload   *message,
                      ProtobufCBuffer     *buffer);
EncryptedPayload *
       encrypted_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   encrypted_payload__free_unpacked
                     (EncryptedPayload *message,
                      ProtobufCAllocator *allocator);
/* LoraHeader methods */
void   lora_header__init
                     (LoraHeader         *message);
size_t lora_header__get_packed_size
                     (const LoraHeader   *message);
size_t lora_header__pack
                     (const LoraHeader   *message,
                      uint8_t             *out);
size_t lora_header__pack_to_buffer
                     (const LoraHeader   *message,
                      ProtobufCBuffer     *buffer);
LoraHeader *
       lora_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora_header__free_unpacked
                     (LoraHeader *message,
                      ProtobufCAllocator *allocator);
/* LoraClientOperationMessage methods */
void   lora_client_operation_message__init
                     (LoraClientOperationMessage         *message);
size_t lora_client_operation_message__get_packed_size
                     (const LoraClientOperationMessage   *message);
size_t lora_client_operation_message__pack
                     (const LoraClientOperationMessage   *message,
                      uint8_t             *out);
size_t lora_client_operation_message__pack_to_buffer
                     (const LoraClientOperationMessage   *message,
                      ProtobufCBuffer     *buffer);
LoraClientOperationMessage *
       lora_client_operation_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora_client_operation_message__free_unpacked
                     (LoraClientOperationMessage *message,
                      ProtobufCAllocator *allocator);
/* ClientRegister methods */
void   client_register__init
                     (ClientRegister         *message);
size_t client_register__get_packed_size
                     (const ClientRegister   *message);
size_t client_register__pack
                     (const ClientRegister   *message,
                      uint8_t             *out);
size_t client_register__pack_to_buffer
                     (const ClientRegister   *message,
                      ProtobufCBuffer     *buffer);
ClientRegister *
       client_register__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_register__free_unpacked
                     (ClientRegister *message,
                      ProtobufCAllocator *allocator);
/* ClientAvailable methods */
void   client_available__init
                     (ClientAvailable         *message);
size_t client_available__get_packed_size
                     (const ClientAvailable   *message);
size_t client_available__pack
                     (const ClientAvailable   *message,
                      uint8_t             *out);
size_t client_available__pack_to_buffer
                     (const ClientAvailable   *message,
                      ProtobufCBuffer     *buffer);
ClientAvailable *
       client_available__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_available__free_unpacked
                     (ClientAvailable *message,
                      ProtobufCAllocator *allocator);
/* ClientBattery methods */
void   client_battery__init
                     (ClientBattery         *message);
size_t client_battery__get_packed_size
                     (const ClientBattery   *message);
size_t client_battery__pack
                     (const ClientBattery   *message,
                      uint8_t             *out);
size_t client_battery__pack_to_buffer
                     (const ClientBattery   *message,
                      ProtobufCBuffer     *buffer);
ClientBattery *
       client_battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   client_battery__free_unpacked
                     (ClientBattery *message,
                      ProtobufCAllocator *allocator);
/* CoverPosition methods */
void   cover_position__init
                     (CoverPosition         *message);
size_t cover_position__get_packed_size
                     (const CoverPosition   *message);
size_t cover_position__pack
                     (const CoverPosition   *message,
                      uint8_t             *out);
size_t cover_position__pack_to_buffer
                     (const CoverPosition   *message,
                      ProtobufCBuffer     *buffer);
CoverPosition *
       cover_position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cover_position__free_unpacked
                     (CoverPosition *message,
                      ProtobufCAllocator *allocator);
/* LoraClientResponseMessage methods */
void   lora_client_response_message__init
                     (LoraClientResponseMessage         *message);
size_t lora_client_response_message__get_packed_size
                     (const LoraClientResponseMessage   *message);
size_t lora_client_response_message__pack
                     (const LoraClientResponseMessage   *message,
                      uint8_t             *out);
size_t lora_client_response_message__pack_to_buffer
                     (const LoraClientResponseMessage   *message,
                      ProtobufCBuffer     *buffer);
LoraClientResponseMessage *
       lora_client_response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lora_client_response_message__free_unpacked
                     (LoraClientResponseMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LoraCoverOperation_Closure)
                 (const LoraCoverOperation *message,
                  void *closure_data);
typedef void (*ClientConfig_Closure)
                 (const ClientConfig *message,
                  void *closure_data);
typedef void (*CoverConfig_Closure)
                 (const CoverConfig *message,
                  void *closure_data);
typedef void (*LoginMsg_Closure)
                 (const LoginMsg *message,
                  void *closure_data);
typedef void (*BaseNonceExchange_Closure)
                 (const BaseNonceExchange *message,
                  void *closure_data);
typedef void (*CommandAck_Closure)
                 (const CommandAck *message,
                  void *closure_data);
typedef void (*EncryptedPayload_Closure)
                 (const EncryptedPayload *message,
                  void *closure_data);
typedef void (*LoraHeader_Closure)
                 (const LoraHeader *message,
                  void *closure_data);
typedef void (*LoraClientOperationMessage_Closure)
                 (const LoraClientOperationMessage *message,
                  void *closure_data);
typedef void (*ClientRegister_Closure)
                 (const ClientRegister *message,
                  void *closure_data);
typedef void (*ClientAvailable_Closure)
                 (const ClientAvailable *message,
                  void *closure_data);
typedef void (*ClientBattery_Closure)
                 (const ClientBattery *message,
                  void *closure_data);
typedef void (*CoverPosition_Closure)
                 (const CoverPosition *message,
                  void *closure_data);
typedef void (*LoraClientResponseMessage_Closure)
                 (const LoraClientResponseMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    cov_operation__descriptor;
extern const ProtobufCEnumDescriptor    client_operation__descriptor;
extern const ProtobufCEnumDescriptor    encryption_algo__descriptor;
extern const ProtobufCEnumDescriptor    ack_status__descriptor;
extern const ProtobufCMessageDescriptor lora_cover_operation__descriptor;
extern const ProtobufCMessageDescriptor client_config__descriptor;
extern const ProtobufCMessageDescriptor cover_config__descriptor;
extern const ProtobufCMessageDescriptor login_msg__descriptor;
extern const ProtobufCMessageDescriptor base_nonce_exchange__descriptor;
extern const ProtobufCMessageDescriptor command_ack__descriptor;
extern const ProtobufCMessageDescriptor encrypted_payload__descriptor;
extern const ProtobufCMessageDescriptor lora_header__descriptor;
extern const ProtobufCMessageDescriptor lora_client_operation_message__descriptor;
extern const ProtobufCMessageDescriptor client_register__descriptor;
extern const ProtobufCMessageDescriptor client_available__descriptor;
extern const ProtobufCMessageDescriptor client_battery__descriptor;
extern const ProtobufCMessageDescriptor cover_position__descriptor;
extern const ProtobufCMessageDescriptor lora_client_response_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_blinds_2eproto__INCLUDED */
