# Schema-drift gate helper. Regenerates blinds.pb-c.{c,h} from the proto in
# PROTO_DIR and compares against the committed stubs.
#
# Two callers with different layouts:
#   COMPARE_AGAINST                     — both stubs in one dir (ESPHome)
#   COMPARE_C_AGAINST / COMPARE_H_AGAINST — split src/ and include/ (the node
#                                           component, IDF's layout)
file(MAKE_DIRECTORY ${OUT_DIR})

if(DEFINED COMPARE_AGAINST)
    set(COMPARE_C_AGAINST ${COMPARE_AGAINST})
    set(COMPARE_H_AGAINST ${COMPARE_AGAINST})
endif()

execute_process(
    COMMAND ${PROTOC_C} --c_out=${OUT_DIR} -I${PROTO_DIR} blinds.proto
    RESULT_VARIABLE rc
    OUTPUT_VARIABLE out
    ERROR_VARIABLE  err)
# protoc-c on Ubuntu 24.04 emits a deprecation notice to stderr but still
# generates files successfully and returns 0. Treat rc==0 as success
# regardless of stderr noise.
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "protoc-c failed (${rc}): ${err}")
endif()

# Version guard.
#
# This gate compares GENERATED TEXT, so it is only meaningful when the local
# protoc-c is the one that produced the committed stubs. It is not: protoc-c
# 1.4.1 and 1.5.2 order oneof members differently and word the version banner
# differently, which the comparison reports as schema drift. That is a false
# positive of the worst kind — it accuses the developer of forgetting to
# regenerate, and the suggested fix (regen_stubs.sh) would commit stubs
# generated by the wrong compiler.
#
# So: read the generator version out of the committed header (protoc-c writes
# it into the PROTOBUF_C_MIN_COMPILER_VERSION guard) and SKIP with a loud
# message when it does not match the local one. A skipped gate that says so is
# honest; a failing gate that is wrong trains people to ignore it.
file(READ ${COMPARE_H_AGAINST}/blinds.pb-c.h _committed_header LIMIT 4096)
string(REGEX MATCH "#elif ([0-9]+) < PROTOBUF_C_MIN_COMPILER_VERSION"
       _m "${_committed_header}")
set(_committed_ver ${CMAKE_MATCH_1})

execute_process(COMMAND ${PROTOC_C} --version
                OUTPUT_VARIABLE _pv ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
string(REGEX MATCH "([0-9]+)\\.([0-9]+)\\.([0-9]+)" _pvm "${_pv}")
math(EXPR _local_ver "${CMAKE_MATCH_1} * 1000000 + ${CMAKE_MATCH_2} * 1000 + ${CMAKE_MATCH_3}")

if(_committed_ver AND NOT _committed_ver EQUAL _local_ver)
    message(STATUS
        "SKIPPED: committed stubs were generated by protoc-c ${_committed_ver}, "
        "local protoc-c is ${_local_ver} (${_pv}). Different protoc-c versions "
        "emit different declaration ORDER, so a text comparison cannot tell "
        "that apart from real schema drift. Install the matching protoc-c to "
        "run this gate.")
    return()
endif()

foreach(stub blinds.pb-c.h blinds.pb-c.c)
    if(stub STREQUAL blinds.pb-c.h)
        set(against ${COMPARE_H_AGAINST})
    else()
        set(against ${COMPARE_C_AGAINST})
    endif()
    execute_process(
        COMMAND ${CMAKE_COMMAND} -E compare_files --ignore-eol
                ${OUT_DIR}/${stub} ${against}/${stub}
        RESULT_VARIABLE diff_rc)
    if(NOT diff_rc EQUAL 0)
        message(FATAL_ERROR
            "${stub} regenerated from ${PROTO_DIR}/blinds.proto differs "
            "from ${against}/${stub}. Either the proto changed and stubs "
            "were not regenerated, or the two copies have drifted. "
            "Fix with: BlindsESP/proto/regen_stubs.sh")
    endif()
endforeach()
