#pragma once
// sdkconfig.h is generated by ESP-IDF menuconfig; on host we don't care.

// --- SPI / radio pin assignment -------------------------------------------
//
// Kconfig-supplied on the real build (components/lora/Kconfig). LoraInterface.h
// uses them as the default arguments of its pin members, so they have to exist
// for the header to compile at all. The VALUES are the node's own, from
// sdkconfig, so a reader of a failing test sees the same numbers as a reader of
// the firmware — and gpios.md's NO_RTC annotation on CS/RST/MISO/MOSI/SCK is
// the reason §11's ULP alternative is dead, which is worth not obscuring here.
#define CONFIG_CS_GPIO   18
#define CONFIG_RST_GPIO  23
#define CONFIG_SCK_GPIO  5
#define CONFIG_MISO_GPIO 19
#define CONFIG_MOSI_GPIO 27
