#pragma once
// sdkconfig.h is generated by ESP-IDF menuconfig; on host we don't care.

// --- SPI / radio pin assignment -------------------------------------------
//
// Kconfig-supplied on the real build (components/lora/Kconfig). LoraInterface.h
// uses them as the default arguments of its pin members, so they have to exist
// for the header to compile at all. The VALUES are the node's own, from
// sdkconfig, so a reader of a failing test sees the same numbers as a reader of
// the firmware — and gpios.md's NO_RTC annotation on CS/RST/MISO/MOSI/SCK is
// the reason §11's ULP alternative is dead, which is worth not obscuring here.
#define CONFIG_CS_GPIO   18
#define CONFIG_RST_GPIO  23
#define CONFIG_SCK_GPIO  5
#define CONFIG_MISO_GPIO 19
#define CONFIG_MOSI_GPIO 27

// --- LoRa fleet key (Tier-1, docs/mac-separation-implementation-plan.md) --
//
// comm_utils.c's derive_aes_gcm_key() now reads this instead of a bare
// literal. MUST match sim/crypto.cpp's kKeyString exactly, or every
// real_cmd_dispatcher_test.cpp/real_lora_client_test.cpp scenario that
// cross-encrypts between the sim harness and this real production code
// fails to decrypt. Intentionally the same test-only, non-production value
// as sim/crypto.cpp — never the real fleet key.
#define CONFIG_BLINDS_LORA_FLEET_KEY "ProtoSimTestKeyNotReal"
