substitutions:
  devicename: "loradevices"



esphome:
  name: $devicename
  # Example configuration entry

  # comment: "MyBlinds"
  # name_add_mac_suffix: true
  # project:
  #   name: "Blinds"
  #   version: "V0.1"

esp32:
  variant: esp32
  cpu_frequency: 240MHz
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_XTAL_FREQ_26: y
      CONFIG_INT_WDT_TIMEOUT_MS: "800"
      CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY: y
      CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK: y
    # advanced:
    #   loop_task_stack_size: 16384
  
preferences:
  flash_write_interval: 30min    

external_components:
  # use all components from a local folder
  - source:
      type: local
      path: local_components

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:
  platform: esphome
  password: "@FelixMarlene1"

wifi:
  ssid: "FRITZ!Box 7590 TD"
  password: "23461468396986328867"
  domain: .fritz.box
  fast_connect: on

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename}-AP"

captive_portal:

# see: https://esphome.io/components/time.html
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 23
        days_of_week: MON-SUN
        then:
          - loracover.on_sleep_start: rol_1



# Enable Web server
web_server:
  port: 80


lora_tracker:
  id: my_lora_tracker


lora_client:
  - id: rol_1
    name: "RollladenWohnzimmer1"
    time_id: homeassistant_time
    short_address: 17
    subnet_address: 02
    sleep_duration: 21600
    mac_address: e0:8c:fe:5f:b7:a4
    

  - id: rol_2
    name: "RollladenWohnzimmer2"
    time_id: homeassistant_time
    short_address: 18
    subnet_address: 02
    sleep_duration: 21600
    mac_address: e0:8c:fe:5f:9e:c4

#mac_address: c4:9e:5f:fe:8c:e0


cover:
  - platform: loracover
    lora_client_id: rol_1
    name: "RollladenWohnzimmer1"
    id: rol_1_cover
    invert_position: false
    open_duration: 60
    close_duration: 60
    blind_height_mm: 2000.0
    axle_diameter_mm: 60.0
    blind_thickness_mm: 8.0

  - platform: loracover
    lora_client_id: rol_2
    name: "RollladenWohnzimmer2"
    id: rol_2_cover
    invert_position: false
    open_duration: 60
    close_duration: 60
    blind_height_mm: 2000.0
    axle_diameter_mm: 60.0
    blind_thickness_mm: 8.0



button:
  - platform: loracover
    lora_client_id: rol_1
    name: "Trigger OTA1"
    id: rol_1_trigger_ota_button
    # type: trigger_ota
  - platform: loracover
    lora_client_id: rol_2
    name: "Trigger OTA2"
    id: rol_2_trigger_ota_button
    # type: trigger_ota

sensor:
  - platform: uptime
    name: '${devicename} Uptime'
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: '${devicename} WiFi Signal'
    update_interval: 300s

  - platform: loracover
    lora_client_id: rol_1
    # cover_id: rol_1
    # name: "RollladenWohnzimmer1 Battery"
    # id: rol_1_battery
    # type: BATTERY
    battery_level:
      name: "RollladenWohnzimmer1 Battery Level"
      id: rol_1_battery_level
    battery_voltage:
      name: "RollladenWohnzimmer1 Battery Voltage"
      id: rol_1_battery_voltage
    link_rssi:
      name: "RollladenWohnzimmer1 Link RSSI"
      id: rol_1_link_rssi
    motor_current:
      name: "RollladenWohnzimmer1 Motor Current"
      id: rol_1_motor_current

  - platform: loracover
    lora_client_id: rol_2
    # cover_id: rol_1
    # name: "RollladenWohnzimmer1 Battery"
    # id: rol_1_battery
    # type: BATTERY
    battery_level:
      name: "RollladenWohnzimmer2 Battery Level"
      id: rol_2_battery_level
    battery_voltage:
      name: "RollladenWohnzimmer2 Battery Voltage"
      id: rol_2_battery_voltage
    link_rssi:
      name: "RollladenWohnzimmer2 Link RSSI"
      id: rol_2_link_rssi
    motor_current:
      name: "RollladenWohnzimmer2 Motor Current"
      id: rol_2_motor_current


binary_sensor:
  - platform: loracover
    lora_client_id: rol_1
    name: "RollladenWohnzimmer1 Command Failed"
    id: rol_1_command_failed
  - platform: loracover
    lora_client_id: rol_2
    name: "RollladenWohnzimmer2 Command Failed"
    id: rol_2_command_failed










