if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/addressing_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/addressing_test[1]_tests.cmake")
else()
  add_test(addressing_test_NOT_BUILT addressing_test_NOT_BUILT)
endif()
