if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/auto_mode_proto_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/auto_mode_proto_test[1]_tests.cmake")
else()
  add_test(auto_mode_proto_test_NOT_BUILT auto_mode_proto_test_NOT_BUILT)
endif()
