if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/cover_config_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/cover_config_test[1]_tests.cmake")
else()
  add_test(cover_config_test_NOT_BUILT cover_config_test_NOT_BUILT)
endif()
