# CMake generated Testfile for 
# Source directory: /mnt/c/Development/esphome/configuration/tests/proto_sim
# Build directory: /mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/register_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/login_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/addressing_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/sleep_wake_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/sysop_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/boundary_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/cover_config_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/reboot_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/race_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/crypto_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/garbage_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/recovery_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/auto_mode_proto_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/lora_timing_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/timed_grid_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mode_a_geometry_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/timed_mode_policy_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/class_a_windows_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mode_a_reliability_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mac_funnel_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mac_sublayers_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/phase_tracker_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/grid_state_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/air_channel_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/sweep_analysis_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/tx_queue_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/ack_cache_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mixed_mode_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mode_test_policy_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/pending_data_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/real_lora_client_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/real_lora_driver_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/real_lora_tracker_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/real_lora_cover_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/scheduler_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/boot_policy_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/auto_mode_policy_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/motor_policy_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/drift_estimator_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/sleep_clock_correction_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/wake_clock_fit_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/schedule_text_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/onboarding_gate_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/timesync_policy_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/frame_crypto_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/session_manager_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/real_cmd_dispatcher_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/seam_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/e2e_test[1]_include.cmake")
include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/real_lora_interface_test[1]_include.cmake")
add_test(schema_drift_hub_vs_esphome "/usr/bin/cmake" "-DPROTOC_C=/usr/local/bin/protoc-c" "-DPROTO_DIR=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/proto" "-DCOMPARE_AGAINST=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/blindsproto" "-DOUT_DIR=/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/stub_regen_hub" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_stub_drift.cmake")
set_tests_properties(schema_drift_hub_vs_esphome PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;143;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(schema_drift_hub_vs_node "/usr/bin/cmake" "-DPROTOC_C=/usr/local/bin/protoc-c" "-DPROTO_DIR=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/proto" "-DCOMPARE_C_AGAINST=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/proto/../components/blinds/src" "-DCOMPARE_H_AGAINST=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/proto/../components/blinds/include" "-DOUT_DIR=/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/stub_regen_node" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_stub_drift.cmake")
set_tests_properties(schema_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;167;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(scheduletext_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/ScheduleText.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/ScheduleText.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(scheduletext_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;415;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(wire_format_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/FrameCrypto.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/FrameCrypto.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(wire_format_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;427;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(scheduler_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/Scheduler.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/Scheduler.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(scheduler_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;446;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(scheduler_impl_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/Scheduler.cpp" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/Scheduler.cpp" "-DALIGN_ON=#include" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(scheduler_impl_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;454;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(loratiming_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/LoraTiming.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/LoraTiming.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(loratiming_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(timedgrid_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/TimedGrid.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/TimedGrid.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(timedgrid_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(timedmodepolicy_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/TimedModePolicy.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/TimedModePolicy.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(timedmodepolicy_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(classawindows_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/ClassAWindows.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/ClassAWindows.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(classawindows_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(macfunnel_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/MacFunnel.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/MacFunnel.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(macfunnel_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(macsublayers_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/MacSublayers.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/MacSublayers.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(macsublayers_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(phasetracker_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/PhaseTracker.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/PhaseTracker.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(phasetracker_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(gridstate_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/GridState.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/GridState.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(gridstate_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(sweepanalysis_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/SweepAnalysis.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/SweepAnalysis.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(sweepanalysis_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(txqueue_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/TxQueue.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/TxQueue.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(txqueue_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(ackcache_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/AckCache.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/AckCache.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(ackcache_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(modetestpolicy_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/ModeTestPolicy.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/ModeTestPolicy.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(modetestpolicy_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
add_test(pendingdata_drift_hub_vs_node "/usr/bin/cmake" "-DSOURCE_HEADER=/mnt/c/Development/PlatformIO/PlatformIO/BlindsESP/main/include/PendingData.h" "-DVENDORED_HEADER=/mnt/c/Development/esphome/configuration/tests/proto_sim/../../local_components/lora_client/PendingData.h" "-P" "/mnt/c/Development/esphome/configuration/tests/proto_sim/cmake/check_header_drift.cmake")
set_tests_properties(pendingdata_drift_hub_vs_node PROPERTIES  LABELS "schema_drift" _BACKTRACE_TRIPLES "/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;478;add_test;/mnt/c/Development/esphome/configuration/tests/proto_sim/CMakeLists.txt;0;")
subdirs("_deps/googletest-build")
