if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/frame_crypto_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/frame_crypto_test[1]_tests.cmake")
else()
  add_test(frame_crypto_test_NOT_BUILT frame_crypto_test_NOT_BUILT)
endif()
