if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/garbage_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/garbage_test[1]_tests.cmake")
else()
  add_test(garbage_test_NOT_BUILT garbage_test_NOT_BUILT)
endif()
