if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/login_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/login_test[1]_tests.cmake")
else()
  add_test(login_test_NOT_BUILT login_test_NOT_BUILT)
endif()
