if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/lora_timing_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/lora_timing_test[1]_tests.cmake")
else()
  add_test(lora_timing_test_NOT_BUILT lora_timing_test_NOT_BUILT)
endif()
