if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mac_funnel_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mac_funnel_test[1]_tests.cmake")
else()
  add_test(mac_funnel_test_NOT_BUILT mac_funnel_test_NOT_BUILT)
endif()
