if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mode_a_geometry_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/mode_a_geometry_test[1]_tests.cmake")
else()
  add_test(mode_a_geometry_test_NOT_BUILT mode_a_geometry_test_NOT_BUILT)
endif()
