if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/mode_test_policy_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/mode_test_policy_test[1]_tests.cmake")
else()
  add_test(mode_test_policy_test_NOT_BUILT mode_test_policy_test_NOT_BUILT)
endif()
