if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/motor_policy_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/motor_policy_test[1]_tests.cmake")
else()
  add_test(motor_policy_test_NOT_BUILT motor_policy_test_NOT_BUILT)
endif()
