if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/pending_data_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/pending_data_test[1]_tests.cmake")
else()
  add_test(pending_data_test_NOT_BUILT pending_data_test_NOT_BUILT)
endif()
