if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/phase_tracker_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/phase_tracker_test[1]_tests.cmake")
else()
  add_test(phase_tracker_test_NOT_BUILT phase_tracker_test_NOT_BUILT)
endif()
