if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/race_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/race_test[1]_tests.cmake")
else()
  add_test(race_test_NOT_BUILT race_test_NOT_BUILT)
endif()
