if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/real_cmd_dispatcher_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/real_cmd_dispatcher_test[1]_tests.cmake")
else()
  add_test(real_cmd_dispatcher_test_NOT_BUILT real_cmd_dispatcher_test_NOT_BUILT)
endif()
