if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/real_lora_tracker_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/real_lora_tracker_test[1]_tests.cmake")
else()
  add_test(real_lora_tracker_test_NOT_BUILT real_lora_tracker_test_NOT_BUILT)
endif()
