if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/reboot_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/reboot_test[1]_tests.cmake")
else()
  add_test(reboot_test_NOT_BUILT reboot_test_NOT_BUILT)
endif()
