if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/recovery_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/recovery_test[1]_tests.cmake")
else()
  add_test(recovery_test_NOT_BUILT recovery_test_NOT_BUILT)
endif()
