if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/register_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/register_test[1]_tests.cmake")
else()
  add_test(register_test_NOT_BUILT register_test_NOT_BUILT)
endif()
