if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/scheduler_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/scheduler_test[1]_tests.cmake")
else()
  add_test(scheduler_test_NOT_BUILT scheduler_test_NOT_BUILT)
endif()
