if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/schedule_text_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/schedule_text_test[1]_tests.cmake")
else()
  add_test(schedule_text_test_NOT_BUILT schedule_text_test_NOT_BUILT)
endif()
