if(EXISTS "/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/seam_test[1]_tests.cmake")
  include("/home/user/esphome_localcomponents/configuration/tests/proto_sim/build_clean/seam_test[1]_tests.cmake")
else()
  add_test(seam_test_NOT_BUILT seam_test_NOT_BUILT)
endif()
