if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/session_manager_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/session_manager_test[1]_tests.cmake")
else()
  add_test(session_manager_test_NOT_BUILT session_manager_test_NOT_BUILT)
endif()
