if(EXISTS "/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/sweep_analysis_test[1]_tests.cmake")
  include("/mnt/c/Development/esphome/configuration/tests/proto_sim/build_clean/sweep_analysis_test[1]_tests.cmake")
else()
  add_test(sweep_analysis_test_NOT_BUILT sweep_analysis_test_NOT_BUILT)
endif()
